version: "3"
services:
  cloud:
    build: ./app/
    restart: always
    environment: 
    - APP_IP=127.0.0.1
    - APP_PORT=3000
    - MONGO_STRING=mongodb://cloud:12345@mongo:27017/
    depends_on:
      - mongo
      # - rproxy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 800m
    volumes:
    - ./cloud/ app:/app
    ports:
    - 8080:3000
  mongo:
    image: mongo
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=cloud
    - MONGO_INITDB_ROOT_PASSWORD=12345
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 550M
    ports:
    - 8081:27017
    volumes:
     - ./data/db:/data/db
     - ./data/configdb:/data/configdb
  rproxy:
    build: ./nginx/
    restart : always
    environment :
    - NGINX_IP=127.0.0.1
    - NGINX_PORT=4000
    - APP_IP=cloud
    - APP_PORT=3000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 450M
    volumes :
      - ./dowonload:/etc/app/shared/
    ports:
    - 8082:4000

